### ISSUE TITLE
Current version/repo uses MD5

### ISSUE THREAD

**Issue by cdietrich** [eclipse-cbi/epl-license-feature#1]
14:51:12  [WARNING] [0d9cb321-6e47-4bf6-b30a-85c65a147978][extension>org.eclipse.tycho:tycho-maven-plugin:3.0.0-SNAPSHOT] The digest algorithms (md5) used to verify org.eclipse.update.feature,org.eclipse.license,2.0.2.v20181016-2210 have severely compromised security. Please report this concern to the artifact provider.

**Comment by laeubi** [comment]
Still seems to be an issue as I see the same problem reported for platfom builds.

**Comment by merks** [comment]
I fixed it just now with these new stronger checksums:
```
        <property name='download.checksum.sha-512' value='e1fdb7b67b6956e339e3a0507f5d264509937e06bbd83f11d9034a9273ec56e8632b4fef1a72be37cb47e67f1953ec509ef35f6c2af69838ea253967ff18d95e'/>
        <property name='download.checksum.sha-256' value='21a87a27db79cd010e47280a9a383dad00f9665ed1a9cb3e8e281701edc14f69'/>
```

**Comment by laeubi** [comment]
Great so I assume you have edited the repository manually somehow and no further actions have to be taken?

**Comment by merks** [comment]
I used the CBI p2 Aggregator locally to aggregate a new repository.  The aggregator creates stronger checksums if they are absent.  I uploaded the two updated artifact metadata files and replaced those in the repository with them.  So yes, this is done.
